package it.polimi.ingsw.am40.server;

import it.polimi.ingsw.am40.server.actions.Action;

/**
 * Interface that ensures the implementation of a method to answer to a notification post
 * in a "listeners" architecture
 */
public interface ActionListener extends ActionAgent{

    /**
     * This method receives an action, generated by an event.
     * Once notified, the implementer must answer to the notification
     * (a call of "onEvent" when a condition is verified).
     * Implementer will call the Action "do" (when "ExampleMessage" is received, do...)
     * @param event The event action. Basing on the information in the message, onEvent do something
     */
    public void onEvent(Action event);
}
