package it.polimi.ingsw.am40;

import it.polimi.ingsw.am40.messages.Message;

/**
 * Interface that ensures the implementation of a method to answer to a notification post
 * in a "listeners" architecture
 */
public interface ActionListener {
    /**
     * This method receives a message, generated by an event.
     * Once notified, the implementer must answer to the notification
     * (a call of "onEvent" when a condition is verified).
     * A "switch-case" approach is recommended (when "ExampleMessage" is received, do...)
     * @param event The event message. Basing on the information in the message, onEvent do something
     */
    public void onEvent(Message event);
}
